# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/10 19:03:45 by marvin            #+#    #+#              #
#    Updated: 2026/01/10 19:03:45 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# voluntarily Makefile is simpler to debug quicker the problems on this libft..

# `make run_test=all` or `make run_test=test_string` runs the comparison suite
# (libc vs ft_malloc: same results + no leaks). Defining run_test on the command
# line redirects the default goal to the test orchestrator.
ifdef run_test
.DEFAULT_GOAL := _run_tests
endif

CC = cc
# -O3: libft is the hot path for the whole shell (memcpy, vectors, strings).
# Building it unoptimized (-O0) made every consumer pay; optimizing it is a
# major, shell-wide win.
CFLAGS = -Wall -Wextra -Werror -D_POSIX_C_SOURCE=200809L -DMINISHELL_DEBUG_PROMPT=1 -std=c99 -O3
PICFLAG = -fPIC
CFLAGS += $(PICFLAG)

BUILD_DIR ?= build
BIN_DIR = $(BUILD_DIR)/bin
LIB_DIR = $(BUILD_DIR)/lib
OBJ_DIR = $(BUILD_DIR)/obj
META_DIR = $(BUILD_DIR)/metadata

NAME = $(LIB_DIR)/libft.a
STATIC_LIB = $(LIB_DIR)/libft.a
SHARED_LIB = $(LIB_DIR)/libft.so

# ---------------------------------------------------------------------------- #
# ft_malloc integration (optional git submodule at srcs/memory/ft_malloc)       #
#                                                                               #
# Checked out (git clone --recursive / git submodule update --init): its        #
# src/*.c are compiled into libft and the fn_* macros (include/xalloc.h) route   #
# every allocation to ft_malloc. Absent: fn_* falls back to libc malloc/free.    #
# The submodule is compiled with ITS OWN flags (not -std=c99 clean, needs        #
# -pthread) by a dedicated rule, and is kept out of the main source glob.        #
# ---------------------------------------------------------------------------- #
FTM_DIR  = srcs/memory/ft_malloc
FTM_SRCS = $(shell find $(FTM_DIR)/src -name "*.c" 2>/dev/null)
CONFIG_H = include/xalloc_config.h
# SAFE=1 forces the libc allocator even when ft_malloc sources are present
# (the parent shell passes SAFE down). SAFE=0 / unset keeps the custom heap.
ifneq ($(strip $(FTM_SRCS)),)
 ifneq ($(SAFE),1)
  HAVE_FTM   := 1
  CFLAGS     += -DHAVE_FT_MALLOC -pthread
  FTM_CFLAGS  = -Wall -Wextra -Werror -fPIC -O3 -pthread -I$(FTM_DIR)/include
  FTM_OBJS    = $(FTM_SRCS:%.c=$(OBJ_DIR)/%.o)
 endif
endif

# Force the allocator switch into every libft TU, regardless of its own
# includes. ft_malloc's own sources use the separate rule below and never see it.
FORCE_XALLOC = -include include/xalloc.h

# Escape hatch for callers (e.g. the test harness) to inject extra flags such as
# -DXALLOC_NO_CONFIG when building cached per-allocator archives.
CFLAGS += $(EXTRA_CFLAGS)

# main libft sources = everything under srcs/ EXCEPT the ft_malloc submodule
SRCS = $(shell find ./srcs -path "./$(FTM_DIR)" -prune -o -name "*.c" -print)
INCS = -I./include -I.
AR = ar rcs
RM = rm -rf
TOTAL = $(words $(SRCS) $(FTM_SRCS))
DEPFLAGS = -MMD -MP -MF
OBJS = $(SRCS:%.c=$(OBJ_DIR)/%.o)
DEPS = $(SRCS:%.c=$(META_DIR)/%.d)
ALL_OBJS = $(OBJS) $(FTM_OBJS)

all : $(STATIC_LIB) $(SHARED_LIB)
	@printf "\r\033[K" >&2
	@printf "\n" >&2
	@printf "  \033[1;33m●\033[0m \033[1;33mlibft\033[0m \033[33m─\033[0m \033[32mcompilation successful\033[0m\n" >&2
	@printf "  \033[33m────────────────────────────────────────\033[0m\n" >&2
	@printf "  \033[32m✓\033[0m \033[37m%s\033[0m\n" "$(STATIC_LIB)" >&2
	@printf "  \033[32m✓\033[0m \033[37m%s\033[0m\n" "$(SHARED_LIB)" >&2
	@printf "\n" >&2

# Bake the active allocator choice into a header so every consumer of libft.h
# inherits it (no -D needed). Rewritten only when the mode actually changes, so
# stable builds don't trigger a recompile.
$(CONFIG_H): FORCE
	@mkdir -p $(dir $@)
	@{ \
		echo '/* AUTO-GENERATED by the libft Makefile — do not edit. */'; \
		echo '#ifndef XALLOC_CONFIG_H'; \
		echo '# define XALLOC_CONFIG_H'; \
		if [ -n "$(HAVE_FTM)" ]; then \
			echo '# ifndef HAVE_FT_MALLOC'; \
			echo '#  define HAVE_FT_MALLOC 1'; \
			echo '# endif'; \
		else \
			echo '/* ft_malloc submodule absent: fn_* -> libc malloc/free */'; \
		fi; \
		echo '#endif'; \
	} > $@.tmp
	@if ! cmp -s $@.tmp $@; then mv $@.tmp $@; else $(RM) $@.tmp; fi

FORCE:
.PHONY: FORCE

# Ensure the config header exists before any libft TU compiles (first build);
# content-change rebuilds are handled by the generated .d dependencies.
$(OBJS): | $(CONFIG_H)

$(STATIC_LIB): $(ALL_OBJS)
	@mkdir -p $(LIB_DIR)
	@$(AR) $@ $^

$(SHARED_LIB): $(ALL_OBJS)
	@mkdir -p $(LIB_DIR)
	@$(CC) -shared -pthread -o $@ $^

# ft_malloc submodule: compiled with its own flags + include path, no force
# header, no -std=c99 (more-specific pattern wins over the generic rule below).
$(OBJ_DIR)/$(FTM_DIR)/%.o : $(FTM_DIR)/%.c
	@mkdir -p $(dir $@)
	@if ! $(CC) $(FTM_CFLAGS) -c $< -o $@; then \
		printf "\n\033[1;31m  ⬢ FT_MALLOC ERROR ⬢\033[0m\n  \033[90m▸\033[0m \033[37m%s\033[0m\n\n" "$<" >&2; \
		exit 1; \
	fi

$(OBJ_DIR)/%.o : %.c
	@mkdir -p $(dir $@)
	@meta_file=$(META_DIR)/$<; meta_file=$${meta_file%.c}.d; mkdir -p "$$(dirname "$$meta_file")"; \
	if ! $(CC) $(CFLAGS) $(FORCE_XALLOC) $(INCS) $(DEPFLAGS) "$$meta_file" -c $< -o $@; then \
	    printf "\n\033[1;31m  ⬢ SYSTEM ERROR ⬢\033[0m\n  \033[90m▸\033[0m \033[37m%s\033[0m\n\n" "$<" >&2; \
	    exit 1; \
	fi
	@mkdir -p $(META_DIR)
	@find . -maxdepth 1 -type f -name ".*" ! -name ".gitignore" ! -name ".gitattributes" ! -name ".git" ! -name "." ! -name ".." -print0 | xargs -0 -r -I{} mv {} $(META_DIR) 2>/dev/null || true
	@count=$$(find $(OBJ_DIR) -name "*.o" 2>/dev/null | wc -l); \
	percent=$$(($$count * 100 / $(TOTAL))); \
	filled=$$(($$percent * 30 / 100)); \
	bar=""; \
	for i in $$(seq 1 30); do \
	    if [ $$i -le $$filled ]; then \
	        bar="$$bar\033[1;36m▰\033[0m"; \
	    else \
	        bar="$$bar\033[90m▱\033[0m"; \
	    fi; \
	done; \
	spin=$$(($$count % 8)); \
	case $$spin in \
	    0) spinner="\033[1;35m⠋\033[0m";; \
	    1) spinner="\033[1;36m⠙\033[0m";; \
	    2) spinner="\033[1;33m⠹\033[0m";; \
	    3) spinner="\033[1;31;5m⠸\033[0m";; \
	    4) spinner="\033[1;32m⠼\033[0m";; \
	    5) spinner="\033[1;34m⠴\033[0m";; \
	    6) spinner="\033[1;37m⠦\033[0m";; \
	    7) spinner="\033[1;96m⠧\033[0m";; \
	esac; \
	printf "\r  $$spinner \033[1;37mLIBFT\033[0m  %b  \033[1;36m%3d%%\033[0m \033[90m%d/%d\033[0m " \
	    "$$bar" $$percent $$count $(TOTAL) >&2;

clean:
	@$(RM) $(OBJ_DIR)
	
fclean : clean
	@$(RM) $(STATIC_LIB) $(SHARED_LIB) $(BUILD_DIR) $(CONFIG_H)

re : fclean all

# Comparison test suite (driven by `make run_test=all` / `make run_test=<name>`).
# bench: `make bench` runs the libc-vs-ft_malloc benchmark.
_run_tests:
	@bash tests/run_tests.sh "$(run_test)"

bench:
	@bash tests/bench.sh

verif_norm:
	@printf "\n  \033[1;36m▸\033[0m Running norminette" >&2; \
	output="$$( \
	    norminette 2>&1 | grep -v 'OK!' | grep -v 'US' & \
	    pid=$$!; \
	    while kill -0 $$pid 2>/dev/null; do \
	        for dots in '.' '..' '...' '....' '.....' '......'; do \
	            printf "\r  \033[1;36m▸\033[0m Running norminette\033[1;35m%-6s\033[0m" "$$dots" >&2; \
	            sleep 0.1; \
	            kill -0 $$pid 2>/dev/null || break; \
	        done; \
	    done; \
	    wait $$pid)"; \
	if [ -z "$$output" ]; then \
	    printf "\r\033[K  \033[1;32m✓\033[0m \033[1;37mNORM CHECK PASSED\033[0m\n\n"; \
	else \
	    printf "\r\033[K  \033[1;31m✗\033[0m \033[1;37mNORM VIOLATIONS:\033[0m\n\n\033[37m%s\033[0m\n\n" "$$output"; \
	fi

.PHONY: all fclean clean re _run_tests bench verif_norm

-include $(DEPS)
