/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   xalloc.h                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: dlesieur <dlesieur@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2026/06/05 00:00:00 by dlesieur          #+#    #+#             */
/*   Updated: 2026/06/05 00:00:00 by dlesieur         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

/*
** Compile-time allocator switch.
**
** Every libc allocation site in libft goes through fn_malloc / fn_calloc /
** fn_realloc / fn_free instead of malloc / calloc / realloc / free:
**
**   HAVE_FT_MALLOC defined   -> the in-house ft_malloc allocator (the git
**                               submodule at srcs/memory/ft_malloc).
**   HAVE_FT_MALLOC undefined -> the system libc allocator.
**
** Both back-ends are thread-safe with identical prototypes, so the switch is
** transparent. fn_* are static inline (the 42 norm forbids function-like
** macros); the FN_BACKEND_* object-like macros pick the back-end at global
** scope, and -O3 folds it all away to zero overhead.
**
** xalloc_config.h is generated by the Makefile and defines HAVE_FT_MALLOC iff
** libft was built with the submodule, so every consumer of libft.h inherits
** the same choice (no -D needed, no cross-allocator free mismatch). If it is
** missing (e.g. editor indexing before a build) we fall back to libc.
*/

#ifndef XALLOC_H
# define XALLOC_H

/*
** XALLOC_NO_CONFIG lets a build select the back-end purely via -D (bypassing the
** generated xalloc_config.h). The test harness uses it to cache a libc and an
** ft archive side-by-side without the single shared config header clashing.
*/
# ifndef XALLOC_NO_CONFIG
#  if defined(__has_include)
#   if __has_include("xalloc_config.h")
#    include "xalloc_config.h"
#   endif
#  else
#   include "xalloc_config.h"
#  endif
# endif

/* Feature-test macros: set before any system header (force-included). */
# ifndef _POSIX_C_SOURCE
#  define _POSIX_C_SOURCE 200809L
# endif
# ifndef _DEFAULT_SOURCE
#  define _DEFAULT_SOURCE
# endif
# ifndef _BSD_SOURCE
#  define _BSD_SOURCE
# endif

# include <stdlib.h>

# ifdef HAVE_FT_MALLOC

/*
** Forward declarations only — including ft_malloc's headers would re-typedef
** t_addr (== void *) and clash with libft under -std=c99. Type-compatible.
*/
void	*ft_malloc(size_t size);
void	*ft_realloc(void *mem, size_t nbytes);
void	*ft_calloc(size_t n, size_t s);
void	ft_free(void *mem);

#  define FN_BACKEND_MALLOC ft_malloc
#  define FN_BACKEND_CALLOC ft_calloc
#  define FN_BACKEND_REALLOC ft_realloc
#  define FN_BACKEND_FREE ft_free

# else

#  define FN_BACKEND_MALLOC malloc
#  define FN_BACKEND_CALLOC calloc
#  define FN_BACKEND_REALLOC realloc
#  define FN_BACKEND_FREE free

# endif

static inline void	*fn_malloc(size_t size)
{
	return (FN_BACKEND_MALLOC(size));
}

static inline void	*fn_calloc(size_t n, size_t size)
{
	return (FN_BACKEND_CALLOC(n, size));
}

static inline void	*fn_realloc(void *ptr, size_t size)
{
	return (FN_BACKEND_REALLOC(ptr, size));
}

static inline void	fn_free(void *ptr)
{
	FN_BACKEND_FREE(ptr);
}

#endif
