name: Build C/C++ Project

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Get your code
    - name: Check out repository
      uses: actions/checkout@v4

    # Step 2: Install dependencies (compiler & build tools)
    - name: Set up compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential

    # Step 3: Build the project
    - name: Compile project
      run: |
        make -j
